### ISSUE TITLE
Aggregator artifact / artifact linked in badge

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-sunrise-java-email#13]
We now updated to the new version, thanks for the Maven badge!

We tried to use the `commercetools-sunrise-email` artifact because it looked like an aggregator whose import would provide us with all artifacts generated from this Git repository. It seemed like this had no effect. At least `email-smtp` was not obtained. We then added a dependency on `email-smtp` which worked for us, presumably because the POM of `email-smtp` served by the Central repository declared this dependency (whereas the POM of `commercetools-sunrise-email` does neither declare modules, nor dependencies).

* Maybe you could adjust the POM generated for `commercetools-sunrise-email` to make it cover `email-api` and `email-smtp`?
* The Maven badge might also point to either the `commercetools-sunrise-email` or the  `email-smtp` artifact to provide users with an implementation alongside the API.

Thanks!

**Comment by lauraluiz** [comment]
@selo-ecube we have pending your request, but it seems the Maven badge we used is down for good after one week broken. We'll be finding a new way soon.

**Comment by lauraluiz** [comment]
Seems it fixed itself :)

**Comment by lauraluiz** [comment]
I've added installation instructions to avoid the same misunderstanding in the future. 
Maybe providing an aggregator would solve the issue for now, but the idea was to provide other ways to send emails by adding more implementations of `email-api`, so there should always be 2 separate dependencies. In Sunrise in particular the dependencies are split: Framework contains the API dependency and a default light one, and then the sunrise-based project adds the second dependency if it wants to change the default one.
