### ISSUE TITLE
Provide an interface with only one method for sending an email

### ISSUE THREAD

**Issue by exx-trost** [commercetools/commercetools-sunrise-java-email#3]
As an abstraction we need an interface "EmailSender" with the following requirements:
- forces the implementation of a method which will be used for sending emails constructed from a [javax.mail.Message](https://javamail.java.net/nonav/docs/api/javax/mail/Message.html) object and returning some kind of identifier if successful :  
  `CompletionStage<String> send(final Message message)` (could have more parameters)
- should be annotated as a functional interface
- use `default` for any additional methods

**Comment by selo-ecube** [comment]
Done with #4
